#!/usr/bin/expect -f
set timeout 20
spawn ssh -p 65002 -o StrictHostKeyChecking=no u445085246@145.79.212.119
expect "password:"
send "Codeforthelife@99\r"
expect -re {\[.*\]\$ }
send "ls -la domains/honeydew-narwhal-750496.hostingersite.com/public_html\r"
expect -re {\[.*\]\$ }
send "cat domains/honeydew-narwhal-750496.hostingersite.com/public_html/.env\r"
expect -re {\[.*\]\$ }
send "cat domains/honeydew-narwhal-750496.hostingersite.com/public_html/api/audit.php | grep -A 5 'OPENROUTER_API_KEY'\r"
expect -re {\[.*\]\$ }
send "curl -I -X POST http://honeydew-narwhal-750496.hostingersite.com/api/audit.php\r"
expect -re {\[.*\]\$ }
send "exit\r"
expect eof
